[workspace]
authors = ["Raphael Druon <raphdruon@gmail.com>"]
channels = ["conda-forge"]
name = "mvp_realsense"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
server = "python realsense_webserver.py"

[dependencies]
python = "==3.12"
pyrealsense2 = ">=2.58.3,<3"
numpy = ">=2,<3"
opencv = ">=4.10,<5"
fastapi = ">=0.115,<1"
uvicorn = ">=0.32,<1"
